-- CreateTable
CREATE TABLE "ArbitrationRequest" (
    "id" TEXT NOT NULL,
    "area" TEXT NOT NULL,
    "applicantType" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "nationalId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "organizationName" TEXT,
    "organizationRegistration" TEXT,
    "representativeName" TEXT,
    "representativePosition" TEXT,
    "disputeType" TEXT NOT NULL,
    "disputeCategory" TEXT NOT NULL,
    "disputeTitle" TEXT NOT NULL,
    "disputeDescription" TEXT NOT NULL,
    "disputeValue" TEXT,
    "disputeDate" TEXT NOT NULL,
    "otherPartyName" TEXT NOT NULL,
    "otherPartyType" TEXT NOT NULL,
    "otherPartyContact" TEXT,
    "otherPartyAddress" TEXT NOT NULL,
    "arbitratorPreference" TEXT NOT NULL,
    "preferredArbitrator" TEXT,
    "excludedArbitrator" TEXT,
    "arbitrationLanguage" TEXT NOT NULL,
    "urgentCase" BOOLEAN NOT NULL DEFAULT false,
    "hasLegalRepresentation" BOOLEAN NOT NULL DEFAULT false,
    "lawyerName" TEXT,
    "lawyerLicense" TEXT,
    "lawyerContact" TEXT,
    "documentsDescription" TEXT NOT NULL,
    "agreesToTerms" BOOLEAN NOT NULL DEFAULT false,
    "agreesToFees" BOOLEAN NOT NULL DEFAULT false,
    "confirmAccuracy" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ArbitrationRequest_pkey" PRIMARY KEY ("id")
);
